# Generated by Django 5.2.12 on 2026-06-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
