# Generated by Django 5.2.12 on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modapi', '0002_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmoderation',
            name='kind',
            field=models.CharField(
                choices=[('CREATE', 'CREATE'), ('EDIT', 'EDIT')],
                default='CREATE',
                max_length=6,
            ),
        ),
    ]
