# Generated by Django 5.2.12 on 2026-06-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_cart_unavailable_reason_product_events'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collectionproduct',
            name='unique_collection_product',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='target_url',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='collectionproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionproduct',
            unique_together={('collection', 'product_id')},
        ),
    ]
