# Generated by Django 5.2.12 on 2026-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('moderator', 'Moderator'), ('seller', 'Seller')], default='client', max_length=20),
        ),
    ]
